name = "HallPIC"
uuid = "2e5be210-d843-4de4-af0b-0054271c24b0"
authors = ["Declan Brick <brickd@umich.edu>", "Thomas Marks <marksta@umich.edu>", "and contributors"]
version = "0.1.0-DEV"

[compat]
Documenter = "1.8.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
