name = "HallPIC"
uuid = "2e5be210-d843-4de4-af0b-0054271c24b0"
authors = ["Declan Brick <brickd@umich.edu>", "Thomas Marks <marksta@umich.edu>", "and contributors"]
version = "0.1.0-DEV"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
DataInterpolations = "7.2.0"
DocStringExtensions = "0.9.3"
Documenter = "1.8.0"
Random = "1.10"
StructArrays = "0.7.0"
julia = "1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
